export const hospitals = [
  "Hospital SAO MATEUS",
  "CHC",
  "HBENTO",
  "AMECOR",
  "FEMINA",
  "HGU",
  "METROPOLITANO",
  "HMC",
  "SANTA ROSA",
  "HILDA STRENGER",
  "REGIONAL DE RONDONOPOLIS",
  "UNIMED CUIABA",
  "UNIMED RONDONOPOLIS",
  "SANTA CASA DE CUIABA",
  "SANTA CASA DE RONDONOPOLIS",
  "SANTA RITA",
  "SANTA ANGELA",
  "HCLINICAS",
  "H SANTA MARIA PRIMAVERA",
]

export const surgeons = [
  "ANDRE MACHADO",
  "MARCEL YAMADA",
  "JOAO CALADO",
  "LUIZ TENORIO",
  "ALEIXO",
  "MARLON",
  "ALEX SANTIAGO",
  "FABIO PEREZ",
  "VINICIUS ANDRADE",
  "HELDER",
  "RUBENS",
  "RENATO BONAFIM",
  "THIAGO AMORIM",
  "CARLOS AUGUSTO",
  "ATILA",
  "BRUNO REGIS",
  "LUCIANO FRANCA",
  "EVERTON",
  "ATHAUALPA",
  "RONAN",
  "KALINIO",
  "CLEITON",
  "RAFAEL KAMICIEK",
  "GUSTAVO BRIANEZE",
  "DOUGLAS GONSALES",
  "VINICIUS NICOLELIS",
  "JOAO AUGUSTO",
  "JOAO OTAVIO",
  "PACAI",
  "PAULO SPRENGLER",
  "DEIVIS FINGER",
  "JOAO CHAVES",
  "SAMUEL",
  "FELIPE BASTOS",
  "EDILSON",
  "GABRIEL CHAVES",
  "CESAR PRADO",
  "GUSTAVO GOBATO",
  "JOSE WESLEY",
  "RENATO DE CARVALHO",
]

export const companies = [
  "TITANIUM",
  "QUALITY",
  "DOCTOR MEDIC",
  "ENDOCARDIO",
  "MEDIC-o",
  "SURGICAL",
  "PACOTE",
  "MEDNEURO",
  "SUS",
  "UNIMED ROO",
  "UNIMED TGA",
]

export const surgeryTypes = [
  { name: "TUMOR CEREBRAL", materialCost: null },
  { name: "TUMOR CEREBRAL COM ATEIO", materialCost: null },
  { name: "TUMOR COLUNA COM ONDA D", materialCost: 1300 },
  { name: "TUMOR COLUNA SEM ONDA D", materialCost: 700 },
  { name: "ESCOLIOSE", materialCost: null },
  { name: "CERVICAL ANTERIOR", materialCost: 700 },
  { name: "TORACICA", materialCost: 700 },
  { name: "LOMBAR", materialCost: 700 },
  { name: "ALIF", materialCost: null },
  { name: "ESTIMULADOR MEDULAR", materialCost: 700 },
  { name: "ANEURISMA", materialCost: null },
  { name: "BASE DE CRANIO COM AEP", materialCost: null },
  { name: "BASE DE CRANIO SEM AEP", materialCost: null },
  { name: "PLEXO CERVICAL", materialCost: 1000 },
  { name: "ATM", materialCost: 500 },
  { name: "TIREOIDE", materialCost: 700 },
]

export const surgeryTypeCosts: Record<string, number | null> = {
  "CERVICAL ANTERIOR": 700,
  "TORACICA": 700,
  "LOMBAR": 700,
  "TUMOR COLUNA COM ONDA D": 1300,
  "TUMOR COLUNA SEM ONDA D": 700,
  "TUMOR CEREBRAL COM ATEIO": 4700,
  "PLEXO CERVICAL": 1000,
  "TIREOIDE": 700,
  "ATM": 500,
  "ESTIMULADOR MEDULAR": 700,
}

export const notificationPhones = [
  { name: "VITORIA", phone: "+5527999060510" },
  { name: "DANILO", phone: "+5519992895009" },
  { name: "MARCELO TOGNATO", phone: "+5511976787140" },
  { name: "MARCELO DIESEL", phone: "+5565981174381" },
]
